INSERT INTO ARTICLE(ID, USER_ID, TITLE, TEXT) VALUES (99, 'user-id', '제목1', '내용123');
INSERT INTO ARTICLE(ID, USER_ID, TITLE, TEXT) VALUES (98, 'user-id', '제목3', '내용333');
INSERT INTO ARTICLE(ID, USER_ID, TITLE, TEXT) VALUES (97, 'user-id', '제목2', '내용222');